[pytest]
asyncio_default_fixture_loop_scope = class
markers = smoke: These are tests tagged as smoke to run only selected tests with smoke tag
        #Here, in Line-3 --> we have registered the word 'smoke' as the marker
        #In Line-2 --> we've assigned the scope to the fixture loop